services:
  # HTTP server for integration tests
  httpbin:
    image: mccutchen/go-httpbin
    ports:
      - "8080:8080"
    networks:
      - test-network

  # MCP Everything server for MCP integration tests
  mcp-everything:
    build:
      context: tests/integration/docker/mcp-everything
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - test-network
    environment:
      - PORT=3001

  # PHP 8.1 container
  php81:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1
    networks:
      - test-network
    environment:
      - TEST_HTTP_SERVER=httpbin:8080
      - TEST_MCP_SERVER=mcp-everything:3001

  # PHP 8.2 container
  php82:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.2
    networks:
      - test-network
    environment:
      - TEST_HTTP_SERVER=httpbin:8080
      - TEST_MCP_SERVER=mcp-everything:3001

  # PHP 8.3 container
  php83:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.3
    networks:
      - test-network
    environment:
      - TEST_HTTP_SERVER=httpbin:8080
      - TEST_MCP_SERVER=mcp-everything:3001

  # PHP 8.4 container
  php84:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.4
    networks:
      - test-network
    environment:
      - TEST_HTTP_SERVER=httpbin:8080
      - TEST_MCP_SERVER=mcp-everything:3001

networks:
  test-network:
    driver: bridge 